# Generated by Django 3.1.7 on 2021-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('proof', models.ImageField(upload_to='customer_proofs')),
                ('status', models.TextField(default='Pending')),
                ('password', models.TextField()),
            ],
        ),
    ]
