# Generated by Django 3.1.7 on 2021-06-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('COD', 'Cash On Delivery')], max_length=3)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.bike')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.station')),
            ],
        ),
        migrations.CreateModel(
            name='BikeRentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date_time', models.DateTimeField(verbose_name='Select From Date Time:')),
                ('to_date_time', models.DateTimeField(verbose_name='Select To Date Time:')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.bike')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.payment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.station')),
            ],
        ),
    ]
