# Generated by Django 3.1.7 on 2021-06-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified')], max_length=1),
        ),
    ]
