# Generated by Django 3.1.7 on 2021-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0002_auto_20210627_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='price_day',
            field=models.PositiveIntegerField(help_text='Enter bike price per day', null=True, verbose_name='Price Per Day'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price_hr',
            field=models.PositiveIntegerField(help_text='Enter bike price per hour', verbose_name='Price Per Hour'),
        ),
    ]
