# Generated by Django 3.1.7 on 2021-06-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0002_bikerenthistory_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikestatus',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Rent')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='bike',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.station'),
        ),
    ]
