# Generated by Django 3.1.7 on 2021-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0003_auto_20210607_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('O', 'Operator')], help_text='Select your role', max_length=1, null=True, verbose_name='Select Your Role'),
        ),
    ]
