# Generated by Django 3.1.7 on 2021-07-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0003_auto_20210628_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='bike',
            field=models.ForeignKey(default=1, help_text='Select Bike', on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.bike'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='station_id',
            field=models.ForeignKey(help_text='Select Station Location', on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.station', verbose_name='Select Station Location'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.ForeignKey(default='', help_text='Select your city', on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.CharField(default='', max_length=50, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.CharField(default='', max_length=50, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='post_code',
            field=models.CharField(default='', max_length=8, verbose_name='Post Code'),
            preserve_default=False,
        ),
    ]
