# Generated by Django 3.1.7 on 2021-06-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0003_auto_20210621_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikecolor',
            field=models.CharField(help_text='Enter bike color', max_length=50, verbose_name='Bike Color'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bikename',
            field=models.CharField(help_text='Enter bike name', max_length=50, verbose_name='Name of Bike'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bikestatus',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Rent')], default='A', max_length=1, verbose_name='Select Bike Status'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brandname',
            field=models.CharField(help_text='Enter bike brand name', max_length=50, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price_day',
            field=models.IntegerField(help_text='Enter bike price per day', null=True, verbose_name='Price Per Day'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price_hr',
            field=models.IntegerField(help_text='Enter bike price per hour', verbose_name='Price Per Hour'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='registered_no',
            field=models.CharField(help_text='Enter bike registered number', max_length=50, verbose_name='Bike Registration Number'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.station', verbose_name='Select Station Location'),
        ),
    ]
