# Generated by Django 3.1.7 on 2021-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0004_auto_20210621_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikestatus',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'On Rent')], default='A', max_length=1, verbose_name='Select Bike Status'),
        ),
    ]
