# Generated by Django 3.1.7 on 2021-07-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0004_auto_20210701_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='bike',
            field=models.ForeignKey(default=None, help_text='Select Bike', on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.bike'),
        ),
    ]
