# Generated by Django 3.1.7 on 2021-06-08 07:03

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0004_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.city')),
            ],
        ),
    ]
