# Generated by Django 3.2.3 on 2021-06-07 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0004_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeid', models.IntegerField(help_text='Enter bike id')),
                ('bikename', models.CharField(help_text='Enter bike name', max_length=50)),
                ('brandname', models.CharField(help_text='Enter bike brand name', max_length=50)),
                ('price_hr', models.IntegerField(help_text='Enter bike price per hour')),
                ('price_day', models.IntegerField(help_text='Enter bike price per day', null=True)),
                ('registered_no', models.CharField(help_text='Enter bike registered number', max_length=50)),
                ('bike_image', models.ImageField(help_text='Add bike image', null=True, upload_to='bike_image')),
                ('bike_manufactured_date', models.DateTimeField(help_text='Add Manufactured date of bike')),
                ('bikecolor', models.CharField(help_text='Enter bike color', max_length=50)),
                ('bikestatus', models.CharField(choices=[('W', 'Working'), ('N', 'Non-Working')], default='W', max_length=1)),
                ('station_id', models.IntegerField(help_text='Enter bike Station id')),
                ('operatorid', models.ForeignKey(help_text='Enter operator id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
