# Generated by Django 3.1.7 on 2021-07-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0005_auto_20210701_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
