# Generated by Django 3.2.3 on 2021-06-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0005_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bikeid',
        ),
    ]
