# Generated by Django 3.2.3 on 2021-06-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0006_remove_bike_bikeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_manufactured_date',
            field=models.DateField(help_text='Add Manufactured date of bike'),
        ),
    ]
