# Generated by Django 3.1.7 on 2021-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0006_auto_20210701_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bike',
            name='registered_no',
            field=models.CharField(help_text='Enter bike registered number', max_length=50, unique=True, verbose_name='Bike Registration Number'),
        ),
    ]
