# Generated by Django 3.1.7 on 2021-06-08 08:39

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0006_auto_20210608_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='address',
        ),
        migrations.RemoveField(
            model_name='station',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='surat', max_length=200),
            preserve_default=False,
        ),
    ]
