# Generated by Django 3.2.3 on 2021-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0007_alter_bike_bike_manufactured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_manufactured_date',
            field=models.DateTimeField(help_text='Add Manufactured date of bike'),
        ),
    ]
