# Generated by Django 3.1.7 on 2021-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0007_auto_20210608_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='location',
        ),
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
