# Generated by Django 3.2.3 on 2021-06-10 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0008_alter_bike_bike_manufactured_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='bikestatus',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Rent')], default='A', max_length=1),
        ),
    ]
