# Generated by Django 3.1.7 on 2021-06-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0008_auto_20210608_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lng',
        ),
        migrations.AddField(
            model_name='station',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='station',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='station',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
