# Generated by Django 3.1.7 on 2021-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0009_auto_20210608_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='town',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='station',
            name='county',
        ),
    ]
