# Generated by Django 3.2.3 on 2021-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0009_auto_20210610_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='star',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.AddField(
            model_name='rating',
            name='suggestions',
            field=models.CharField(default='Good', help_text='Enter your suggestion', max_length=50),
        ),
    ]
