# Generated by Django 3.1.7 on 2021-06-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0010_auto_20210608_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='district',
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(help_text='Select your city', null=True, on_delete=django.db.models.deletion.CASCADE, to='BikeUsers.city'),
        ),
    ]
