# Generated by Django 3.2.3 on 2021-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0011_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_image',
            field=models.FileField(help_text='Add bike image', null=True, upload_to='bike_image'),
        ),
    ]
