# Generated by Django 3.1.7 on 2021-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeUsers', '0011_auto_20210609_1202'),
        ('BikeUsers', '0006_remove_bike_bikeid'),
    ]

    operations = [
    ]
